name: Test Notify

on:
  push:
    branches:
    - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: notify
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TOKEN }}
        repository: taiking/test-github-action
        event-type: update